-- CreateTable
CREATE TABLE `total_units` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `totalUnits` INTEGER NOT NULL DEFAULT 18,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
