-- CreateTable
CREATE TABLE `subject_schedules` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sourceId` VARCHAR(191) NULL,
    `subjectId` VARCHAR(191) NOT NULL,
    `subject` VARCHAR(191) NOT NULL,
    `subjectCode` VARCHAR(191) NOT NULL,
    `subjectName` VARCHAR(191) NOT NULL,
    `subjectDescription` VARCHAR(191) NULL,
    `faculty` VARCHAR(191) NOT NULL,
    `facultyId` VARCHAR(191) NOT NULL,
    `facultyName` VARCHAR(191) NOT NULL,
    `room` VARCHAR(191) NOT NULL,
    `roomId` VARCHAR(191) NOT NULL,
    `roomName` VARCHAR(191) NOT NULL,
    `time` VARCHAR(191) NOT NULL,
    `day` VARCHAR(191) NOT NULL,
    `days` VARCHAR(191) NULL,
    `startTime` VARCHAR(191) NOT NULL,
    `endTime` VARCHAR(191) NOT NULL,
    `semester` VARCHAR(32) NOT NULL,
    `academicYear` VARCHAR(16) NOT NULL,
    `program` VARCHAR(32) NOT NULL,
    `yearLevel` VARCHAR(32) NOT NULL,
    `credits` INTEGER NOT NULL,
    `units` INTEGER NOT NULL,
    `type` VARCHAR(191) NOT NULL,
    `students` VARCHAR(191) NULL,
    `section` VARCHAR(191) NULL,
    `tags` JSON NULL,
    `hasConflict` BOOLEAN NULL,
    `status` VARCHAR(191) NULL,
    `conflictType` VARCHAR(191) NULL,
    `department` VARCHAR(191) NULL,
    `curriculumId` INTEGER NULL,
    `instructorId` INTEGER NULL,
    `roomLegacyId` INTEGER NULL,
    `isActive` BOOLEAN NULL DEFAULT true,
    `generationId` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `subject_schedules_department_academicYear_semester_yearLevel_idx`(`department`, `academicYear`, `semester`, `yearLevel`, `program`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `subject_schedules` ADD CONSTRAINT `subject_schedules_generationId_fkey` FOREIGN KEY (`generationId`) REFERENCES `schedule_generations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
